version: '3.9'
services:
  dev:
    container_name: cryptomath-api-mailer-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - rabbitmq
  prod:
    container_name: cryptomath-api-mailer-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    container_name: cryptomath-api-mailer-rabbitmq
    hostname: rabbitmq
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'